name: .NET

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Cache nuget package
      id: cacheStep
      uses: actions/cache@v2
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
        restore-keys: |
          ${{ runner.os }}-nuget-
    - name: Restore dependencies
      if: steps.cacheStep.outputs.cache-hit != 'true'
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Debug --no-restore
    - name: Publish
      run: dotnet publish --configuration Debug --no-build
    - uses: actions/upload-artifact@v2
      with:
        name: artifact1
        path: ./cicdfirst/bin/Debug/netcoreapp3.1/publish/

      
